### ISSUE TITLE
Will you dual license this as MIT too?

### ISSUE THREAD

**Issue by pdebruic** [nevins-b/javascript-bcrypt#18]
I'm not a lawyer and wouldn't want to use this in client projects because I'm unsure of the consequences of the GPLv3 vs the MIT license for the rest of the project.  So is it possible you'd consider dual licensing this as both GPL and MIT?   Thanks

**Comment by nevins-b** [comment]
I'm not a lawyer either, that being said after doing a little review of the differences between the GPL and MIT licensing I don't see a problem changing the project over to use the MIT license.

I don't see that this will affect anyone is currently using the project since the MIT license is more open.

**Comment by pdebruic** [comment]
Thanks
